### PR TITLE
Add support paging for GetUserVideos method.

### PR DESCRIPTION
**Pull request by mfilippov**

### CODE REVIEW

**Comment by scommisso** [comment]
Would either of you want to maintain this repo? I'd be happy to transfer it.

**Comment by mfilippov** [comment]
Ok i can maintain this repo. But also i’m need access to update NuGet package.
--
Mikhail Filippov	
IT Director
Sky@Net (Home Computer Networks ltd.)
phone: +7-920-185-0001
e-mail: mikhail@filippov.me <mailto:mikhail@filippov.me>
skype: filippovma

**Comment by scommisso** [comment]
Awesome, I'll transfer it now. I'll figure out the NuGet side also.

**Comment by scommisso** [comment]
What's your NuGet username?

**Comment by scommisso** [comment]
I can't transfer Repo ownership until your fork is removed, also.

**Comment by mfilippov** [comment]
I remove my own fork.
---
Mikhail Filippov	
IT Director
Sky@Net (Home Computer Networks ltd.)
phone: +7-920-185-00-01
e-mail:mikhail@filippov.me <mailto:mikhail.filippov@me.com>
Skype:filippovma
ICQ: 262248663

**Pull request merged**
